post:
  tags:
    - Inventory Usage
  summary: Approve inventory usage
  description:
  parameters:
    - name: id
      in: path
      required: true
      description: Inventory Usage ID
      schema:
        type: integer
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  id:
                    type: integer
                  warehouse_id:
                    type: integer
                  employee_id:
                    type: integer
                  form:
                    type: object
                    properties:
                      id:
                        type: integer
                      branch_id:
                        type: integer
                      date:
                        type: string
                        format: date
                      number:
                        type: string
                      edited_number:
                        type: string
                      edited_notes:
                        type: string
                      notes:
                        type: string
                      created_by:
                        type: integer
                      updated_by:
                        type: integer
                      done:
                        type: integer
                      increment:
                        type: integer
                      increment_group:
                        type: integer
                      formable_id:
                        type: integer
                      formable_type:
                        type: string
                      request_approval_to:
                        type: integer
                      request_approval_at:
                        type: string
                        format: date
                      approval_by:
                        type: integer
                      approval_at:
                        type: string
                        format: date
                      approval_reason:
                        type: integer
                      approval_status:
                        type: integer
                      request_cancellation_to:
                        type: integer
                      request_cancellation_by:
                        type: integer
                      request_cancellation_at:
                        type: string
                        format: date
                      request_cancellation_reason:
                        type: string
                      cancellation_approval_at:
                        type: string
                        format: date
                      cancellation_approval_by:
                        type: integer
                      cancellation_approval_reason:
                        type: string
                      cancellation_status:
                        type: integer
                      created_at:
                        type: string
                        format: date
                      updated_at:
                        type: string
                        format: date
    '422':
      description: Unprocessable entity